project:
  type: book
  output-dir: docs

book:
  title: "GIS와 지리교육"
  author: "김세창"
  date: "2024. 6. 8."
  repo-url: https://github.com/Sechang-Kim/GIS_and_Geoedu/
  repo-actions: issue
  chapters:
    - index.qmd
    - static-interactive-table.qmd
    - static-interactive-plot-1.qmd
    - static-interactive-plot-2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    grid:
      sidebar-width: 250px
      body-width: 1000px
      margin-width: 250px
      gutter-width: 1.0rem
    theme:
      - custom.scss
    mainfont: Pretendard

editor: visual
