---
title: "GIS와 지리교육"
author: "김세창"
format: html
editor: visual
---

# Welcome {.unnumbered}

전국지리교사모임(전지모) 선생님들께

안녕하세요, 서울대학교 지리교육과 김세창입니다. 이 페이지는 오늘 발표의 마지막 파트, **"[지리교육에서 GIS가 나아갈 수 있는 방향]{.underline}"**을 보여드리고자 제작되었습니다.

당연하게도 제가 말씀드릴 내용 말고도 다양한 방향이 있을 수 있고, 심지어 더 좋은 방향이 있을수도 있습니다. 다만 저를 포함해 제 지도교수님인 이상일 교수님, 함께 공부하고 있는 김우형과 전헤민 학생이 최근 구상하고 있는 바를 보여드리고자 합니다.

먼저 용어를 정리하는 것이 좋을 것 같습니다. 흔히 우리는 GIS를 '지도 제작 프로그램' 정도로 지칭하여 이야기합니다. 그래서 지리교육에 GIS를 활용한다고 하면 GIS 프로그램을 사용한 지리교육을 떠올립니다. 아시는 분들은 아시겠지만, 대표적으로 ArcGIS, QGIS, SGIS 정도가 있습니다. 여기서 ArcGIS는 데스크톱에 설치해서 사용하는 상용 소프트웨어, QGIS는 데스크톱에 설치해서 사용하는 무료 소프트웨어, SGIS는 웹에 접속해서 사용하는 웹 서비스입니다. 그런데 이러한 용례는 사실 굉장히 좁은 의미의 것입니다. 넓은 의미에서 보자면, GIS는 "공간정보를 시각화하고 분석하는 일련의 과정" 정도라고 볼 수 있겠습니다. 제가 여기서 말하는 "GIS 활용 지리교육"에서 GIS는 바로 이 넓은 의미를 지칭한다고 생각해주시면 좋겠습니다. 왜일까요?

이는 좁은 의미에서의 "GIS"는 교육현장에 적용되기 사실상 불가능하기 때문입니다. 많은 선생님들께서 공감하시겠지만, 컴퓨터를 활용해서 교과를 가르치기란 무척 어렵습니다. 아마 다음과 같은 문제점이 있을 것입니다.

-   나가야 할 진도만 나가도 시간이 부족한데, 언제 프로그램을 설치하나요?
-   프로그램에서 요상한(?) 오류가 발생하면 언제 해결해주나요?
-   교사는 그 어려운 프로그램을 언제 배우나요?
-   정보 시간과 겹쳐서 컴퓨터실이 부족하면 어떻게 하나요?

최근 AI나 데이터 사이언스가 매우 유행하게 되면서, GIS라는 분야 역시 '데이터 사이언스'의 일환으로 바라볼 수 있게 되었습니다. 즉 GIS는 데이터의 한 종류인 공간정보를 다룰 뿐, 여타의 데이터 사이언스와 다를 것이 없다는 것입니다. 그런 의미에서 GIS를 "공간 데이터 사이언스(Spatial Data Science)"그런데 아시다시피 2022 개정 교육과정의 주요 안건은 "데이터 리터러시"입니다.

When you click the **Render** button a document will be generated that includes both content and the output of embedded code. You can embed code like this:

```{r}
#| echo: false
#| message: false
#| warning: false

library(tidyverse)
library(gapminder)
library(DT)

datatable(gapminder)
```
